topics:
  - name: nav
    topic: /cmd_vel_nav
    timeout: 0.5
    priority: 50
  - name: avoid
    topic: /cmd_vel_avoid
    timeout: 0.5
    priority: 80
  - name: teleop
    topic: /cmd_vel_teleop
    timeout: 0.5
    priority: 100

locks:
  - name: estop
    topic: /e_stop
    timeout: 0.0
    priority: 255
